boostjp/site

tips/network/tcp.md
timer_.cancel() が間に合わない場合を考慮するようにしました．
=> correct timeout example with asio timer class

tips/signals.md
boost::signal2 の自動コネクション管理の項目を追加しました。よろしくお願いします。
=> 自動コネクション管理の項目追加

document.md
こんにちは。稚拙ですが、Boost.Coroutine2のドキュメントを訳した（リファレンス以外ですが）ので、掲載いただけると幸いです。
https://www.gitbook.com/book/kumar8600/boost-coroutine2-doc-ja/details
以上、よろしくお願いいたします :sushi:
=> ドキュメントにBoost.Coroutine2の日本語訳へのリンクを追加

document/version/1_66_0.md
=> Optional の 翻訳を追加

archive/boost_docs/libs/date_time/class_date.md
=> fix: Broken accessors table layout

document/version/1_67_0.md
=> [1.67 リリースノート] Log の翻訳を追加

document/version/1_67_0.md
=> Stacktrace の翻訳を追加

document/version/1_67_0.md
=> Optional の翻訳を追加

document/version/1_67_0.md
=> Beast のリリースノートの翻訳を追加

document/version/1_67_0.md
=> [1.67 リリースノート] Fiber の翻訳を追加

document/version/1_67_0.md
=> [1.67 リリースノート] Test の翻訳を追加

archive/boost_docs/libs/date_time/print_month.cpp.md
サンプルコードが欠けてしまっている(？)箇所を修正しました。
=> fix: Example code of Print Month.

document/version/1_69_0.md
=> [1.69.0 リリースノート] Lexical Cast の翻訳を追加

document/version/1_69_0.md
=> [1.69.0 リリースノート] Multiprecision の翻訳を追加

document/version/1_69_0.md
=> [1.69.0 リリースノート] Context の翻訳を追加

document/version/1_69_0.md
=> [1.69.0 リリースノート] Math の翻訳を追加

tips/parser.md
Fix #411
#411 のサンプルコード修正のPull Requestになります。
`main()`を追加してコピー＆ペーストで実行できるようにしてあります。
=> サンプルコードの修正 #411

tips/optional.md
`tips/optional.md`内のtypoを修正しました。
=> typoを修正 (rigth -> right)

communities.md
リンク切れに気が付きまして、このままも気持ちが悪いので、取り消し線にしてみましたが…
どうでしょうか？
=> コミュニティページのリンク切れが分かるように記載

.github/workflows/build.yml, boostcon/2011.md, cppnow/2012.md, study_meeting/study10.md, study_meeting/study12.md, study_meeting/study14.md, study_meeting/study7.md
https://github.com/cpprefjp/site_generator/pull/81
=> 内部リンクを相対リンクで生成する機能 (cpprefjp/site_generator#81)
